export default [
  'Lorem ipsum dolor sit amet, consectetur adipisicing elit.',
  'Lorem ipsum, dolor sit amet consectetur adipisicing elit. Totam eveniet consectetur fugiat sint sit reiciendis, numquam ad, doloremque cum quo nostrum. Excepturi dolorum recusandae perspiciatis, error omnis eius minus ipsa.',
  'Lorem ipsum dolor sit amet consectetur adipisicing elit. Vitae veniam perferendis corporis omnis facilis',
  'Lorem ipsum dolor sit amet, consectetur adipisicing elit.',
  'Lorem ipsum, dolor sit amet consectetur adipisicing elit. Totam eveniet consectetur fugiat sint sit reiciendis, numquam ad, doloremque cum quo nostrum. Excepturi dolorum recusandae perspiciatis, error omnis eius minus ipsa.',
  'Lorem ipsum dolor sit amet consectetur adipisicing elit. Vitae veniam perferendis corporis omnis facilis',
  'Lorem ipsum, dolor sit amet consectetur adipisicing elit. Totam eveniet consectetur fugiat sint sit reiciendis, numquam ad, doloremque cum quo nostrum. Excepturi dolorum recusandae perspiciatis, error omnis eius minus ipsa.',
  'Lorem ipsum dolor sit amet consectetur adipisicing elit. Vitae veniam perferendis corporis omnis facilis',
  'Lorem ipsum dolor sit amet consectetur adipisicing elit. Vitae veniam perferendis corporis omnis facilis',
  'Lorem ipsum, dolor sit amet consectetur adipisicing elit. Totam eveniet consectetur fugiat sint sit reiciendis, numquam ad, doloremque cum quo nostrum. Excepturi dolorum recusandae perspiciatis, error omnis eius minus ipsa.',
  'Lorem ipsum dolor sit amet consectetur adipisicing elit. Vitae veniam perferendis corporis omnis facilis',
  'Lorem ipsum dolor sit amet, consectetur adipisicing elit.',
  'Lorem ipsum, dolor sit amet consectetur adipisicing elit. Totam eveniet consectetur fugiat sint sit reiciendis, numquam ad, doloremque cum quo nostrum. Excepturi dolorum recusandae perspiciatis, error omnis eius minus ipsa.',
  'Lorem ipsum dolor sit amet consectetur adipisicing elit. Vitae veniam perferendis corporis omnis facilis',
  'Lorem ipsum, dolor sit amet consectetur adipisicing elit. Totam eveniet consectetur fugiat sint sit reiciendis, numquam ad, doloremque cum quo nostrum. Excepturi dolorum recusandae perspiciatis, error omnis eius minus ipsa.',
  'Lorem ipsum dolor sit amet consectetur adipisicing elit. Vitae veniam perferendis corporis omnis facilis',
  'Lorem ipsum dolor sit amet, consectetur adipisicing elit.',
  'Lorem ipsum, dolor sit amet consectetur adipisicing elit. Totam eveniet consectetur fugiat sint sit reiciendis, numquam ad, doloremque cum quo nostrum. Excepturi dolorum recusandae perspiciatis, error omnis eius minus ipsa.',
  'Lorem ipsum dolor sit amet consectetur adipisicing elit. Vitae veniam perferendis corporis omnis facilis',
  'Lorem ipsum dolor sit amet, consectetur adipisicing elit.',
];
